config/routes.rb
Expat::Application.routes.draw do
  comfy_route :cms_admin, :path => "/#{ENV['CMS_FOLDER']}"
  resources :managers
  resources :accounts
  resources :consultants
  resources :contacts, only: [:new, :create]
  match '/contact-us', to: 'contacts#new', via: 'get'
  match '/getting-started', to: 'contacts#new', via: 'get'
  match '/2013 US Tax Questionnaire.xlsx', to: 'contacts#getform', via: 'get'
  match '/captchaurl', to: 'captcha#captchaImage', via: 'get'
  match '/test_message', to: 'contacts#message', via: 'get'

  match "/#{ENV['GOOGLE']}.html", to: proc { |env| [200, {},
    ["google-site-verification: #{ENV['GOOGLE']}.html"]] }, via: 'get'
  match "/#{ENV['SITETRAIL']}.html", to: proc { |env| [200, {},
    ["#{ENV['SITETRAIL']}.html"]] }, via: 'get'

  
  comfy_route :cms, :path => '/', :sitemap => true

end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  has_many :accounts
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :password, length: { minimum: 6 }
  has_secure_password
  
  before_create do
    self.password = "consultant"
    self.password_confirmation = "consultant"
  end

end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  http_basic_authenticate_with name: ENV['TRACKER_USERNAME'], password: ENV['TRACKER_PASSWORD']
  layout "tracker"
  protect_from_forgery with: :exception

  def index
    @consultants = Consultant.all
  end

  def new
    @consultant = Consultant.new
  end
  def create
    @consultant = Consultant.new(consultant_params)
    @consultant.password = "consultant"
    @consultant.password_confirmation = "consultant"
    if @consultant.save
      flash[:success] = "You have created a new consultant"
      redirect_to '/consultants'
    else
      render 'new'
    end
  end

  def edit
    @consultant = Consultant.find(params[:id])
  end
  def update
    @consultant = Consultant.find(params[:id])
    @consultant.password = "consultant"
    @consultant.password_confirmation = "consultant"
    if @consultant.update_attributes(consultant_params)
      flash[:success] = "Consultant Edited successfully"
      redirect_to '/consultants'
    else
      @consultant = Consultant.find(params[:id])
      render 'edit'
    end
  end

  def destroy
    Consultant.find(params[:id]).destroy
    flash[:success] = "Consultant destroyed permanently"
    redirect_to '/consultants'
  end

  private

    def consultant_params
      params.require(:consultant).permit(:name, :password, :password_confirmation)
    end

end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/edit.html.erb
<% provide(:title, 'Edit Consultant') %>
<h1>Editing <%= @consultant.name %></h1>

<div id="consultant" class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@consultant) do |f| %>
      <%= render 'shared/consultant_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>

      <%= f.submit "Update #{@consultant.name}", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to "Delete #{@consultant.name}", @consultant, method: :delete, data: { confirm: "STOP!!  This action is irreversible!" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/consultants/index.html.erb
<% provide(:title, 'All consultants') %>
<h1>All Consultants</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <ul class="consultants">
      <% @consultants.each do |con| %>
	<li><%= link_to con.name, edit_consultant_path(con) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/consultants/new.html.erb
<% provide(:title, 'New Consultant') %>
<h1>Create New Consultant</h1>

<div id="consultant" class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@consultant) do |f| %>
      <%= render 'shared/consultant_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
      
      <%= f.submit "Create Consultant", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>