config/routes.rb
Expat::Application.routes.draw do
  comfy_route :cms_admin, :path => "/#{ENV['CMS_FOLDER']}"
  resources :managers
  resources :accounts
  resources :consultants
  resources :contacts, only: [:new, :create]
  match '/contact-us', to: 'contacts#new', via: 'get'
  match '/getting-started', to: 'contacts#new', via: 'get'
  match '/2013 US Tax Questionnaire.xlsx', to: 'contacts#getform', via: 'get'
  match '/captchaurl', to: 'captcha#captchaImage', via: 'get'
  match '/test_message', to: 'contacts#message', via: 'get'

  match "/#{ENV['GOOGLE']}.html", to: proc { |env| [200, {},
    ["google-site-verification: #{ENV['GOOGLE']}.html"]] }, via: 'get'
  match "/#{ENV['SITETRAIL']}.html", to: proc { |env| [200, {},
    ["#{ENV['SITETRAIL']}.html"]] }, via: 'get'

  
  comfy_route :cms, :path => '/', :sitemap => true

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_many :accounts
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :password, length: { minimum: 6 }
  has_secure_password
  
  before_create do
    self.password = "manager"
    self.password_confirmation = "manager"
  end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  http_basic_authenticate_with name: ENV['TRACKER_USERNAME'], password: ENV['TRACKER_PASSWORD']
  layout "tracker"
  protect_from_forgery with: :exception
  
  def index
    @managers = Manager.all.order('updated_at DESC')
  end

  def new
    @manager = Manager.new
  end
  def create
    @manager = Manager.new(manager_params)
    @manager.password = "manager"
    @manager.password_confirmation = "manager"
    if @manager.save
      flash[:success] = "You have created a new manager"
      redirect_to '/managers'
    else
      render 'new'
    end
  end

  def edit
    @manager = Manager.find(params[:id])
  end
  def update
    @manager = Manager.find(params[:id])
    @manager.password = "manager"
    @manager.password_confirmation = "manager"
    if @manager.update_attributes(manager_params)
      flash[:success] = "Manager Edited successfully"
      redirect_to '/managers'
    else
      @manager = Manager.find(params[:id])
      render 'edit'
    end
  end

  def destroy
    Manager.find(params[:id]).destroy
    flash[:success] = "Manager destroyed permanently"
    redirect_to '/managers'
  end

  private

    def manager_params
      params.require(:manager).permit(:name, :password, :password_confirmation)
    end

end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/edit.html.erb
<% provide(:title, 'Edit Manager') %>
<h1>Editing <%= @manager.name %></h1>

<div id="consultant" class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@manager) do |f| %>
      <%= render 'shared/manager_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>

      <%= f.submit "Update #{@manager.name}", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to "Delete #{@manager.name}", @manager, method: :delete, data: { confirm: "STOP!!  This action is irreversible!" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/managers/index.html.erb
<% provide(:title, 'All managers') %>
<h1>All Managers</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <ul class="consultants">
      <% @managers.each do |man| %>
	<li><%= link_to man.name, edit_manager_path(man) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/managers/new.html.erb
<% provide(:title, 'Create New Manager') %>
<h1>Create New Manager</h1>

<div id="consultant" class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= form_for(@manager) do |f| %>
      <%= render 'shared/manager_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>

      <%= f.submit "Create Manager", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>