config/routes.rb
Expat::Application.routes.draw do
  comfy_route :cms_admin, :path => "/#{ENV['CMS_FOLDER']}"
  resources :managers
  resources :accounts
  resources :consultants
  resources :contacts, only: [:new, :create]
  match '/contact-us', to: 'contacts#new', via: 'get'
  match '/getting-started', to: 'contacts#new', via: 'get'
  match '/2013 US Tax Questionnaire.xlsx', to: 'contacts#getform', via: 'get'
  match '/captchaurl', to: 'captcha#captchaImage', via: 'get'
  match '/test_message', to: 'contacts#message', via: 'get'

  match "/#{ENV['GOOGLE']}.html", to: proc { |env| [200, {},
    ["google-site-verification: #{ENV['GOOGLE']}.html"]] }, via: 'get'
  match "/#{ENV['SITETRAIL']}.html", to: proc { |env| [200, {},
    ["#{ENV['SITETRAIL']}.html"]] }, via: 'get'

  
  comfy_route :cms, :path => '/', :sitemap => true

end

app/views/layouts/_contact_form.html.erb
<%= form_for @contact, html: {id: "loose-form", class: "left", role: "form"} do |f| %>
  <%= render 'shared/error_messages.html' %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :company %>
    <%= f.text_field :company, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :foreign, "Foreign Country of Residence" %>
    <%= f.text_field :foreign, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone, "Phone (If you desire to be contacted by phone)" %>
    <%= f.phone_field :phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label(:years, "How many years previous are you filing for?") %>
    <div class="clear"></div>
    <%= f.radio_button(:years, "1") %>
    <%= f.label(:years_1, "1") %>
    <%= f.radio_button(:years, "2") %>
    <%= f.label(:years_2, "2") %>
    <%= f.radio_button(:years, "3 or more") %>
    <%= f.label(:years_3, "3 or more") %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Additional Comments" %>
    <%= f.text_area :body, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box(:quote) %>
    <%= f.label(:quote, "Reply with fee quote for US expatriate tax services") %>
  </div>
  <div class="form-group">
    <%= f.check_box(:individual) %>
    <%= f.label(:individual, "Reply with fee quote for U.S. individual tax services") %>
  </div>
  <div class="form-group">
    <%= f.check_box(:corporate) %>
    <%= f.label(:corporate, "Reply with fee quote for U.S. corporate tax services") %>
  </div>
  <div class="form-group">
    <%= f.check_box(:gaapfee) %>
    <%= f.label(:gaapfee, "Reply with fee quote for US GAAP translation services") %>
  </div>
  <div class="form-group">
    <%= f.check_box(:gaap) %>
    <%= f.label(:gaap, "Have a consultant contact me regarding US GAAP translation services") %>
  </div>
  <div class="form-group">
    <%= f.check_box(:russian) %>
    <%= f.label(:russian, "Reply with fee quote for Russian tax services") %>
  </div>
  <div class="form-group">
  <%= render 'simple_captcha/simple_captcha' %>
  <%= f.submit "Send Message", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <h6>Expat CPA | Cloud-Based Tax Preparation | American Expatriate Tax Services | US Expat Tax | &copy;2014 | All Rights Reserved</h6> 
  <h6>info@expatcpa.com - (714) 939-7670 - One City Boulevard West, Suite 870, Orange, CA 92868</h6>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <div class="col-xs-5">
      <%= image_tag "http://d21c7j241p6103.cloudfront.net/banner/expatcpa_banner4.png", alt: "Expat CPA US expatriate tax", id: "ban-logo" %>
    </div>
    <div id="gallery" class="col-xs-7">
    </div>
  </div>
  <div class="clear"></div>
  <nav class="navbar navbar-default" role="navigation"> 
    <ul class="nav">
      <% page = Cms::Site.first.pages.root %>
      <li class="cameo"><%= link_to page.label, page.full_path %></li>
      <% Cms::Site.first.pages.root.children.published.each do |page| %>
	<li class="dropdown cameo">
	  <%= link_to page.label, page.full_path, class: "dropdown-toggle", :data => {:toggle => "dropdown"} %>
	  <% if page.children.published.any? %>
	    <ul class="dropdown-menu">
	      <% if page.full_path == "/about" %>
		<li><%= link_to page.label, page.full_path %></li>
	      <% end %>
	      <% page.children.published.each do |child| %>
		<li><%= link_to child.label, child.full_path %></li>
	      <% end %>
	    </ul>
	  <% end %>
	</li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_pop_worker.html.erb
<% worker = @cms_site.files.images.for_category('lgworker').sort_by(&:label).first %>
<% unless worker.blank? %>
<%= image_tag(worker.file.url, class: "w100") %>
<%= worker.description.html_safe %>
<% end %>

app/views/layouts/_pop_worker.mobile.erb
<% @cms_site.files.images.for_category('smworker').sort_by(&:label).each do |fl| %>
  <%= image_tag fl.file.url, class: "head-shot" %>
  <%= Cms::File.for_category('lgworker').find_by_label(fl.label).description.html_safe %>
  <div class="clear"></div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <script src="/respond.js"></script>
  <link href="http://d3qubnvmt6127p.cloudfront.net/cross-domain/respond-proxy.html" id="respond-proxy" rel="respond-proxy" />
  <link href="/cross-domain/respond.proxy.gif" id="respond-redirect" rel="respond-redirect" />
  <script src="/cross-domain/respond.proxy.js"></script>
<![endif]-->

app/views/layouts/_standard_head.html.erb
<% meta [:name => 'msapplication-TileColor', :content => "#FFFFFF"],
	[:name => 'msapplication-TileImage', :content => asset_path('favicon-144.png')] %>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <% if @cms_page.blank? then %>
  <%= metamagic :title => full_title(yield(:title)),
		:description => "Certified Public Accountant services for expatriates" %>
  <% else %>
  <%= metamagic :title => full_title(cms_page_content(:seo_title)),
		:description => cms_page_content(:seo_description) %>
  <% end %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'favicon-152.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true, :async => Rails.env.production? %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_testify.html.erb
<% res = ""
 Cms::Site.first.snippets.for_category('testimony').each do |snip|
  res += "'"
  res += Jhelp.escape_js snip.content
  res += "', "
end %>
testify([<%= res.html_safe %>]);

app/views/layouts/_testimonials.html.erb
<div id="testify-page">
<% @cms_site.snippets.for_category('testimony').each do |snip| %>
  <%= snip.content.html_safe %>
<% end %>
</div>

app/views/layouts/_track_nav.html.erb
<nav id="track-nav" class="navbar navbar-default" role="navigation"> 
  <ul id="track-nav" class="nav">
    <li class="cameo"><%= link_to "list accounts", accounts_path %></li>
    <li class="cameo"><%= link_to "create account", new_account_path %></li>
    <li class="cameo"><%= link_to "list managers", managers_path %></li>
    <li class="cameo"><%= link_to "create manager", new_manager_path %></li>
    <li class="cameo"><%= link_to "list consultants", consultants_path %></li>
    <li class="cameo"><%= link_to "create consultant", new_consultant_path %></li>
    <li class="cameo pull-right" style="margin-right: 20px; font-size: 1.2em;"><%= link_to "EXPATCPA CLOUD", 'https://expatcpa.syncedtool.com' %></li>
    <li class="cameo pull-right" style="margin-right: 10px; font-size: 1.2em;"><%= link_to "CCH PROSYSTEM", 'https://office.prosystemfx.com' %></li>
  </ul>
</nav>

app/views/layouts/_workers.html.erb
<% @cms_site.files.images.for_category('smworker').sort_by(&:label).each do |fl| %>
  <%= image_tag(fl.file.url, class: "head-shot button-fade", onClick: "swapWorker('#{fl.label}')".html_safe) %>
<% end %>

app/views/layouts/application.mobile.erb
<% meta [:name => 'msapplication-TileColor', :content => "#FFFFFF"],
	[:name => 'msapplication-TileImage', :content => asset_path('favicon-144.png')] %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name=viewport content="width=device-width, initial-scale=1">
    <% if @cms_page.blank? then %>
    <%= metamagic :title => full_title(yield(:title)),
		  :description => "Certified Public Accountant services for expatriates" %>
    <% else %>
    <%= metamagic :title => full_title(cms_page_content(:seo_title)),
		  :description => cms_page_content(:seo_description) %>
    <% end %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'favicon-152.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= stylesheet_link_tag "mobapp", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= link_to (image_tag("expatcpa_banner2.jpg", alt: "ExpatCPA")), '/' %>
      <div class="link-box">
	<% Cms::Site.first.pages.root.children.published.each do |page| %>
	<%= link_to page.label, page.full_path %>
	<% end %>
      </div>
    </header>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <div class="link-box">
        <% if @cms_page && @cms_page.children.published.any? %>
        <h3>More:</h3>
	  <% @cms_page.children.published.each do |page| %>
	  <%= link_to page.label, page.full_path %>
	  <% end %>
	<% end %>
      </div>
      <%= render 'layouts/footer.html' %>
    </div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48110982-1', 'expatcpa.com');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/layouts/error_frame.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", media: "all",
					    "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= render 'layouts/shim' %>
  </head>
  <body class="center">
    <div id="whole-background" class="w100 pa">
      <div class="w100" id="black-band"></div>
      <div class="w100" id="white-touch"></div>
      <div class="w100" id="gradient-band"></div>
    </div>
    <div class="pr">
      <div id="container-wrapper">
      <div class="container">
	<div class="clear"></div>
	<header>
	  <div class="row">
	    <div class="col-xs-4 col-xs-offset-1">
	      <%= image_tag "expatcpa_banner2.jpg", id: "ban-logo" %>
	    </div>
	    <div id="gallery" class="col-xs-5 col-xs-offset-1">
	      <%= image_tag "empty.jpg", id: "place-holder" %>
	    </div>
	  </div>
	  <div class="clear"></div>
	  <nav class="navbar navbar-default" role="navigation"> 
	    <ul class="nav">
	      <li class="cameo"><%= link_to 'home', '/' %></li>
	      <li class="dropdown cameo">
		<%= link_to "contact us", '/contact-us' %>
	      </li>
	    </ul>
	  </nav>
	</header>
	<%= yield %>
	<%= render 'layouts/footer' %>
      </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/tracker.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", media: "all",
					    "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body class="center">
    <div id="whole-background" class="w100 pa">
      <div class="w100" id="black-band"></div>
      <div class="w100" id="white-touch"></div>
      <div class="w100" id="gradient-band"></div>
    </div>
    <div class="pr">
      <div id="container-wrapper">
	<div class="container">
	  <div class="clear"></div>
	  <header>
	    <%= image_tag "expatcpa_banner.jpg", class: "w100" %>
	    <%= render 'layouts/track_nav' %>
	  </header>
	  <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>
	  <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
	</div>
      </div>
    </div>
  </body>
</html>