config/routes.rb
Expat::Application.routes.draw do
  comfy_route :cms_admin, :path => "/#{ENV['CMS_FOLDER']}"
  resources :managers
  resources :accounts
  resources :consultants
  resources :contacts, only: [:new, :create]
  match '/contact-us', to: 'contacts#new', via: 'get'
  match '/getting-started', to: 'contacts#new', via: 'get'
  match '/2013 US Tax Questionnaire.xlsx', to: 'contacts#getform', via: 'get'
  match '/captchaurl', to: 'captcha#captchaImage', via: 'get'
  match '/test_message', to: 'contacts#message', via: 'get'

  match "/#{ENV['GOOGLE']}.html", to: proc { |env| [200, {},
    ["google-site-verification: #{ENV['GOOGLE']}.html"]] }, via: 'get'
  match "/#{ENV['SITETRAIL']}.html", to: proc { |env| [200, {},
    ["#{ENV['SITETRAIL']}.html"]] }, via: 'get'

  
  comfy_route :cms, :path => '/', :sitemap => true

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :manager
  belongs_to :consultant
  
  validates :name, presence: true
  
  before_save do
    sub = 0
    sub = sub + (basic ? 299 : 0)
    sub = sub + (state ? 175 : 0)
    sub = sub + (f1116 ? 135 : 0)
    sub = sub + (a ? 85 : 0)
    sub = sub + (b ? 35 : 0)
    sub = sub + (c ? 125 : 0)
    sub = sub + (d ? 75 : 0)
    sub = sub + (e ? 125 : 0)
    sub = sub + (extension ? 75 : 0)
    sub = sub + (f ? 75 : 0)
    sub = sub + (f8938 ? 75 : 0)
    sub = sub + (f5471 ? 600 : 0)
    sub = sub + (misc || 0)
    
    self.fee = sub
    self.cost = sub * 0.4
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  http_basic_authenticate_with name: ENV['TRACKER_USERNAME'], password: ENV['TRACKER_PASSWORD']
  layout "tracker"
  protect_from_forgery with: :exception

  def index
    @accounts = Account.all
    render layout: "widescreen"
  end

  def new
    @account = Account.new
  end
  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:success] = "You have created a new account"
      redirect_to '/accounts'
    else
      render 'new'
    end
  end

  def edit
    @account = Account.find(params[:id])
  end
  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(account_params)
      flash[:success] = "Account was updated successfully"
      redirect_to '/accounts'
    else
      render 'edit'
    end
  end

  def destroy
    Account.find(params[:id]).destroy
    flash[:success] = "Account destroyed permanently"
    redirect_to '/accounts'
  end

  private

    def account_params
      params.require(:account).permit!
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_fields.html.erb
<div class="col-md-6">
    <%= f.label :name, "Account Name" %>
    <%= f.text_field :name, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :manager_id, "Manager" %>
    <%= f.collection_select(:manager_id, Manager.all, :id, :name) %>
    <div class="clear"></div>

    <%= f.label :consultant_id, "Consultant" %>
    <%= f.collection_select(:consultant_id, Consultant.all, :id, :name) %>
    <div class="clear"></div>
    
    <%= f.label :received, "Quest/Note Received" %>
    <%= f.date_field :received, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :assigned, "Return Assigned" %>
    <%= f.date_field :assigned, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :began, "Began processing return" %>
    <%= f.date_field :began, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :completed, "Return Completed" %>
    <%= f.date_field :completed, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :sent, "Sent to Client" %>
    <%= f.date_field :sent, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :filed, "E Filed" %>
    <%= f.date_field :filed, :class => "form-control" %>
    <div class="clear"></div>

    <%= f.label :status, "Account Status" %>
    <%= f.select(:status, options_for_select([['Normal', 1], ['Awaiting Data',2], ['Client Not Responding',3], ['Client Quit',4]], @account.status)) %>
    <div class="clear"></div>
</div>
<div class="col-md-6" style="text-align: right;">
    <%= f.check_box(:basic) %>
    <%= f.label(:basic, "1040/2555 Basic") %>
    <div class="clear"></div>

    <%= f.check_box(:state) %>
    <%= f.label(:state, "State") %>
    <div class="clear"></div>

    <%= f.check_box(:f1116) %>
    <%= f.label(:f1116, "Form 1116") %>
    <div class="clear"></div>

    <%= f.check_box(:a) %>
    <%= f.label(:a, "Schedule A") %>
    <div class="clear"></div>

    <%= f.check_box(:b) %>
    <%= f.label(:b, "Schedule B") %>
    <div class="clear"></div>

    <%= f.check_box(:c) %>
    <%= f.label(:c, "Schedule C") %>
    <div class="clear"></div>

    <%= f.check_box(:d) %>
    <%= f.label(:d, "Schedule D") %>
    <div class="clear"></div>

    <%= f.check_box(:e) %>
    <%= f.label(:e, "Schedule E") %>
    <div class="clear"></div>

    <%= f.check_box(:extension) %>
    <%= f.label(:extension, "Filing Extension") %>
    <div class="clear"></div>

    <%= f.check_box(:f) %>
    <%= f.label(:f, "Form TD F 90-22.1") %>
    <div class="clear"></div>

    <%= f.check_box(:f8938) %>
    <%= f.label(:f8938, "Form 8938") %>
    <div class="clear"></div>

    <%= f.check_box(:f5471) %>
    <%= f.label(:f5471, "Form 5471") %>
    <div class="clear"></div>
    <div class="bump-down"></div>

    <%= f.label :name, "Additional Charges" %>
    <%= f.text_field :misc, :class => "form-control" %>
    <div class="clear"></div>
    
    <h3>Payments Received From Client</h3>
    <%= f.label :deposit, "Initial Deposit" %>
    <%= f.text_field :deposit, :class => "form-control" %>
    <div class="clear"></div>
    
    <%= f.label :payment, "Additional Receipts" %>
    <%= f.text_field :payment, :class => "form-control" %>
</div>

app/views/accounts/edit.html.erb
<% provide(:title, 'Edit Account') %>
<h1>Editing <%= @account.name %> Account</h1>

<div id="tight-form" class="row">
  <%= render 'shared/account_messages' %>
    <%= form_for(@account, html: {role: "form"} ) do |f| %>
      <%= render 'fields', f: f %>
      <div class="clear"></div>
      <%= f.submit "Update #{@account.name}", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to "Delete #{@account.name}", @account, method: :delete, data: { confirm: "STOP!!  This action is irreversible!" }, class: "btn btn-danger" %>
</div>

app/views/accounts/index.html.erb
<% provide(:title, 'All accounts') %>
<table class="table datatable">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>manager</th>
      <th>consultant</th>
      <th>received</th>
      <th>assigned</th>
      <th>began</th>
      <th>completed</th>
      <th>sent</th>
      <th>filed</th>
      <th>basic</th>
      <th>state</th>
      <th>1116</th>
      <th>Sch A</th>
      <th>Sch B</th>
      <th>Sch C</th>
      <th>Sch D</th>
      <th>Sch E</th>
      <th>Extension</th>
      <th>TD F</th>
      <th>8938</th>
      <th>5471</th>
      <th>misc</th>
      <th>fee</th>
      <th>Deposit</th>
      <th>Payment</th>
      <th>Balance</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% i = 0
  fees = 0
  costs = 0
  balances = 0
  deposits = 0
  payments = 0
  @accounts.order("lower(name) ASC").each do |acc|
  i = i + 1
  fees = fees + (acc.fee || 0)
  deposits = deposits + (acc.deposit || 0)
  payments = payments + (acc.payment || 0)
  balance = (acc.fee || 0) - (acc.deposit || 0) - (acc.payment || 0)
  balances = balances + balance %>
  <tr>
    <td><%= i %></td>
    <td><%= link_to acc.name, edit_account_path(acc) %></td>
    <td><%= acc.manager.name unless acc.manager.blank? %></td>
    <td><%= acc.consultant.name unless acc.consultant.blank? %></td>
    <td><%= acc.received.strftime("%b %d") unless acc.received.blank? %></td>
    <td><%= acc.assigned.strftime("%b %d") unless acc.assigned.blank? %></td>
    <td><%= acc.began.strftime("%b %d") unless acc.began.blank? %></td>
    <td><%= acc.completed.strftime("%b %d") unless acc.completed.blank? %></td>
    <td><%= acc.sent.strftime("%b %d") unless acc.sent.blank? %></td>
    <td><%= acc.filed.strftime("%b %d") unless acc.filed.blank? %></td>
    <td class="checks"><%= "299" if acc.basic %></td>
    <td class="checks"><%= "175" if acc.state %></td>
    <td class="checks"><%= "135" if acc.f1116 %></td>
    <td class="checks"><%= "85" if acc.a %></td>
    <td class="checks"><%= "35" if acc.b %></td>
    <td class="checks"><%= "125" if acc.c %></td>
    <td class="checks"><%= "75" if acc.d %></td>
    <td class="checks"><%= "125" if acc.e %></td>
    <td class="checks"><%= "75" if acc.extension %></td>
    <td class="checks"><%= "75" if acc.f %></td>
    <td class="checks"><%= "75" if acc.f8938 %></td>
    <td class="checks"><%= "600" if acc.f5471 %></td>
    <td><%= number_to_currency(acc.misc) %></td>
    <td><%= number_to_currency(acc.fee) %></td>
    <td>-<%= number_to_currency(acc.deposit) %></td>
    <td>-<%= number_to_currency(acc.payment) %></td>
    <td><%= number_to_currency(balance) %></td>
    <% if acc.manager.name == "Soucie" || acc.manager.name == "Winters" || acc.manager.name == "Choudhury" || acc.manager.name == "Rachel" || acc.manager.name == "Michael" %>
      <% costs = costs + (acc.cost || 0) %>
      <td><%= number_to_currency(acc.cost) %></td>
    <% else %>
      <td></td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
  <tfoot>
    <tr><%= ("<td></td>" * 23).html_safe %>
      <td><%= number_to_currency(fees) %></td>
      <td>-<%= number_to_currency(deposits) %></td>
      <td>-<%= number_to_currency(payments) %></td>
      <td><%= number_to_currency(balances) %></td>
      <td><%= number_to_currency(costs) %></td>
    </tr>
  </tfoot>
</table>

app/views/accounts/new.html.erb
<% provide(:title, 'Create New Account') %>
<h1>Create New Account</h1>

<div id="tight-form" class="row">
  <%= render 'shared/account_messages' %>
    <%= form_for(@account, html: {role: "form"} ) do |f| %>
      <%= render 'fields', f: f %>
      <div class="clear"></div>
      <%= f.submit "Create Account", class: "btn btn-large btn-primary" %>
    <% end %>
</div>